### ISSUE TITLE
Which Csu-XX package to use with what Mac OSX?

### ISSUE THREAD

**Issue by skaht** [argoneus/apple-csu-79#1]
This is more of a comment than an issue, albeit 4 years later.

Bookmark http://www.opensource.apple.com/.  If you drill down through it, you see what Mac OSX versions require which Csu-XX packages. 

In summary, OSX 10.6 - 10.9 use Csu-79. Yosemite (10.0) starts to use Csu-85.

FYSA - I have a very strong hunch this Mac crt0.o static linking issue was the major hurdle that was preventing me from successfully building GNU-based ARM Beagle Bone Black (BBB) cross compiler toolchain on my 10.8 Mac last year.

**Comment by skaht** [comment]
Here is the trick to compile on a Mac OS X 10.10 platform. Two header files are missing within the Csu-79 package when you try to execute make. They are located with the 10.10 SDK. 
"make ARCH_CFLAGS=-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include" compiled everything for me. An "ls -l" after the make yields:

-rw-r--r--@  1 Scott  staff   5301 Feb  8 17:24 Makefile
-rw-r--r--   1 Scott  staff    520 Feb  8 17:32 bundle1.v1.o
-rw-r--r--@  1 Scott  staff  11895 Oct  8  2013 crt.c
-rw-r--r--   1 Scott  staff    592 Feb  8 17:32 crt0.o
-rw-r--r--   1 Scott  staff   1928 Feb  8 17:32 crt1.v1.o
-rw-r--r--   1 Scott  staff    920 Feb  8 17:32 crt1.v2.o
-rw-r--r--   1 Scott  staff    800 Feb  8 17:32 crt1.v3.o
-rw-r--r--   1 Scott  staff    800 Feb  8 17:32 crt1.v4.o
-rw-r--r--@  1 Scott  staff   7479 Oct  8  2013 dyld_glue.s
-rw-r--r--   1 Scott  staff    520 Feb  8 17:32 dylib1.v1.o
-rw-r--r--   1 Scott  staff    520 Feb  8 17:32 dylib1.v2.o
-rw-r--r--   1 Scott  staff   2216 Feb  8 17:32 gcrt1.o
-rw-r--r--@  1 Scott  staff   1083 Oct  8  2013 icplusplus.c
-rw-r--r--@  1 Scott  staff   8166 Oct  8  2013 lazy_dylib_helper.s
-rw-r--r--@  1 Scott  staff   8176 Oct  8  2013 lazy_dylib_loader.c
-rw-r--r--   1 Scott  staff   3168 Feb  8 17:32 lazydylib1.o
-rw-r--r--@  1 Scott  staff   8145 Oct  8  2013 start.s

**Comment by argoneus** [comment]
@skaht Thanks for the note.  I haven't revisited this in several years, but I appreciate the updated info that you provide here!
